#!/bin/bash

# Check for root privileges
if [ "$EUID" -ne 0 ]; then
  echo "Please run this script with root privileges (use sudo)."
  exit 1
fi

# Define a list of packages and applications to install
packages_to_install=(
    wget
    bashtop
    htop
    neofetch
    vim
    vlc
    nvme-cli
    net-tools
    ssh
    cmake
    build-essential
    libssl-dev
    flatpak
    gnome-shell-extension-manager
    gnome-shell-extensions
    gnome-tweaks
    stacer
    timeshift
    winehq-staging
    keepassxc
    org.supertuxproject.SuperTux
)

# Add Flathub repository for Flatpak
flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo

# Update repositories and install essential packages
sudo apt update
sudo apt install -y "${packages_to_install[@]}"

# Install Flatpak applications
flatpak install flathub -y com.spotify.Client com.discordapp.Discord com.jetbrains.IntelliJ-IDEA-Community com.jetbrains.IntelliJ-IDEA-Ultimate com.getpostman.Postman us.zoom.Zoom

# Install Wine
sudo dpkg --add-architecture i386
wget -nc https://dl.winehq.org/wine-builds/winehq.key
sudo mv winehq.key /etc/apt/trusted.gpg.d/winehq.gpg
sudo sh -c 'echo "deb https://dl.winehq.org/wine-builds/ubuntu/ $(lsb_release -cs) main" > /etc/apt/sources.list.d/winehq.list'
sudo apt update
sudo apt install --install-recommends -y winehq-staging

# Add repositories and install required packages
sudo add-apt-repository ppa:phoerious/keepassxc -y
sudo apt update
sudo apt install -y keepassxc

# Download VMware for a 30-day free trial
wget https://download3.vmware.com/software/WKST-1700-LX/VMware-Workstation-Full-17.0.0-20800274.x86_64.bundle

# Make the downloaded bundle file executable
chmod +x VMware-Workstation-Full-17.0.0-20800274.x86_64.bundle

# Run the VMware Workstation installer
./VMware-Workstation-Full-17.0.0-20800274.x86_64.bundle

